name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai flask
          pip install aliyun-python-sdk-core==2.15.1

      - name: 设置环境变量
        run: |
          echo "API_KEY=${{ secrets.DEEPSEEKKEY }}" >> $GITHUB_ENV
          echo "API_KEY_ALI=${{ secrets.ALIKEY }}" >> $GITHUB_ENV

      - name: 检查 API_KEY 是否正确加载
        run: echo "API_KEY is set to $API_KEY"
        env:
          API_KEY: ${{ secrets.DEEPSEEKKEY }}

      - name: 运行 DeepSeekApi.py
        run: python WebSite/DeepSeek/DeepSeekApi.py
        env:
          API_KEY: ${{ secrets.DEEPSEEKKEY }}

      - name: 运行 app.py
        run: python WebSite/app.py
        env:
          API_KEY: ${{ secrets.ALIKEY }}