name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置环境变量
        run: echo "API_KEY=${{ secrets.DEEPSEEKKEY }}" >> $GITHUB_ENV

      - name: 检查 API_KEY 是否正确加载
        run: echo "API_KEY is set to $API_KEY"
        env:
          API_KEY: ${{ secrets.DEEPSEEKKEY }}

      - name: 运行 Python 脚本
        run: python /home/runner/work/WebSite/DeepSeek/DeekSeekApi.py

        env:
          API_KEY: ${{ secrets.DEEPSEEKKEY }}
